# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170830_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
