# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 10:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_channel_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='channels', to=settings.AUTH_USER_MODEL),
        ),
    ]
