# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_channel_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='channel',
            name='members',
        ),
    ]
