# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170911_0341'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together=set([('company', 'name')]),
        ),
    ]
